# -*- coding: utf-8 -*-
"""Question 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QI6NjSxtIdksB8h1WRktadPMT2k2kTfV
"""

import matplotlib.pyplot as plt
import numpy as np

# create 1000 equally spaced points between -10 and 10
x = np.linspace(1, 2, 1000)

# calculate the y value for each element of the x vector
y =  4 - 8*x + 3*(x**2)

fig, ax = plt.subplots()
ax.plot(x, y)
f = np.array(range(2))
f_y = 1 - 2*f





plt.plot(f,f_y)
plt.ylim(-1.5,1)
plt.xlim(0,2)
plt.xlabel('x')
plt.ylabel('P(x)')
plt.title('Plot of Piecewise function P(x)')
plt.show()