# -*- coding: utf-8 -*-
"""Question 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xUjQTHR13K_1aQbM-Brlb7Z2KUO-fE1h
"""

import matplotlib.pyplot as plt 
years_after = [0,20,40, 60,80, 100]
population_mill = [76.0, 105.7, 131.7, 179.3, 226.5, 281.4]

plt.plot(years_after, population_mill)
plt.xlabel('Years after 1900')
plt.ylabel('Population in millions')
plt.title('Population of US between 1900 and 2000')
plt.show()