# -*- coding: utf-8 -*-
"""Question 15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123kNhmkmxdtosr3hNugQ2TcAHg3n-Vns
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate
from scipy.interpolate import CubicSpline
x = [0,1,2,3,4,5,6]
y = [0,1,2,3,4,5,6]
z = np.array([[0,0,0,2,0,0,0],[0,0,0,2,0,0,0], [0,0,2,4,2,0,0], [1,2,4,8,4,2,2], [0,0,2,4,2,0,0], [1,2,4,8,4,2,2], [0,0,2,4,2,0,0],[0,0,0,2,0,0,0], [0,0,0,1,0,0,0]])
f = CubicSpline(x,y, bc_type='natural')
x_new = np.linspace(0,6,61)
y_new = f(x_new)

plt.figure(figsize = (10,8))
plt.plot(x_new, y_new, 'b')
plt.plot(x, y, 'ro')
plt.title('Cubic Spline Interpolation')
plt.xlabel('x')
plt.ylabel('y')
plt.show()